In [ ]:
'''
Practiacl no.1

Title: Data Wrangling,I

Aim: Perform the following operations using Python on any open source dataset (e.g., 
data.csv) Import all the required Python Libraries. 
1. Locate open source data from the web (e.g. https://www.kaggle.com). 
2. Provide a clear description of the data and its source (i.e., URL of the web site). 
3. Load the Dataset into the pandas data frame. 
4. Data Preprocessing: check for missing values in the data using pandas insult(), 
describe() function to get some initial statistics. Provide variable descriptions. Types 
of variables etc. Check the dimensions of the data frame. 
5. Data Formatting and Data Normalization: Summarize the types of variables by 
checking the data types (i.e., character, numeric, integer, factor, and logical) of the 
variables in the data set. If variables are not in the correct data type, apply proper type 
conversions. 
6. Turn categorical variables into quantitative variables in Python. 

Objective:
Students should be able to perform the data wrangling operation using Python on any open source dataset'''

In [2]:
import pandas as pd                    
from sklearn import preprocessing

In [3]:
df = pd.read_csv("Iris.csv")

In [4]:
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [5]:
df.isnull()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [6]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [7]:
df.isna()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [ ]:
# head tail index shape columns.dtypes,column.values, .iloc[]

In [8]:
df.head(n=5)         #returns first five rows

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
df.tail(n=5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [10]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [11]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [12]:
df.shape

(150, 6)

In [13]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [14]:
df.columns.values

array(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
       'PetalWidthCm', 'Species'], dtype=object)

In [15]:
df.describe(include='all')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,150.000000,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,Iris-setosa
freq,NaN,NaN,NaN,NaN,NaN,50
mean,75.500000,5.843333,3.054000,3.758667,1.198667,NaN
std,43.445368,0.828066,0.433594,1.764420,0.763161,NaN
min,1.000000,4.300000,2.000000,1.000000,0.100000,NaN
25%,38.250000,5.100000,2.800000,1.600000,0.300000,NaN
50%,75.500000,5.800000,3.000000,4.350000,1.300000,NaN
75%,112.750000,6.400000,3.300000,5.100000,1.800000,NaN
max,150.000000,7.900000,4.400000,6.900000,2.500000,NaN

In [16]:
df['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [17]:
df.sort_index(axis=1,ascending=False)

,Species,SepalWidthCm,SepalLengthCm,PetalWidthCm,PetalLengthCm,Id
0,Iris-setosa,3.5,5.1,0.2,1.4,1
1,Iris-setosa,3.0,4.9,0.2,1.4,2
2,Iris-setosa,3.2,4.7,0.2,1.3,3
3,Iris-setosa,3.1,4.6,0.2,1.5,4
4,Iris-setosa,3.6,5.0,0.2,1.4,5
...,...,...,...,...,...,...
145,Iris-virginica,3.0,6.7,2.3,5.2,146
146,Iris-virginica,2.5,6.3,1.9,5.0,147
147,Iris-virginica,3.0,6.5,2.0,5.2,148
148,Iris-virginica,3.4,6.2,2.3,5.4,149
149,Iris-virginica,3.0,5.9,1.8,5.1,150

In [18]:
df.sort_values(by="SepalLengthCm")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica

In [19]:
df.iloc[5]

Id                         6
SepalLengthCm            5.4
SepalWidthCm             3.9
PetalLengthCm            1.7
PetalWidthCm             0.4
Species          Iris-setosa
Name: 5, dtype: object

In [20]:
df[0:3]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [21]:
df.loc[:, ["SepalLengthCm", "PetalLengthCm"]]

     SepalLengthCm  PetalLengthCm
0              5.1            1.4
1              4.9            1.4
2              4.7            1.3
3              4.6            1.5
4              5.0            1.4
..             ...            ...
145            6.7            5.2
146            6.3            5.0
147            6.5            5.2
148            6.2            5.4
149            5.9            5.1

[150 rows x 2 columns]

In [22]:
df.iloc[:6, :]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [23]:
df.iloc[:, :5]

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [24]:
df.iloc[:5,:6]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [25]:
df.iloc[3:5, 0:2]

   Id  SepalLengthCm
3   4            4.6
4   5            5.0

In [26]:
df.iloc[[1, 2, 4], [0, 2]]

   Id  SepalWidthCm
1   2           3.0
2   3           3.2
4   5           3.6

In [27]:
df.iloc[1:3, :]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [28]:
df.iloc[:, 1:3]

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

In [29]:
df.iloc[1, 1]

np.float64(4.9)

In [30]:
df['SepalLengthCm'].iloc[5]

np.float64(5.4)

In [31]:
cols_2_4=df.columns[2:4] 
df[cols_2_4]

     SepalWidthCm  PetalLengthCm
0             3.5            1.4
1             3.0            1.4
2             3.2            1.3
3             3.1            1.5
4             3.6            1.4
..            ...            ...
145           3.0            5.2
146           2.5            5.0
147           3.0            5.2
148           3.4            5.4
149           3.0            5.1

[150 rows x 2 columns]

In [32]:
df[df.columns[2:4]].iloc[5: 10]

   SepalWidthCm  PetalLengthCm
5           3.9            1.7
6           3.4            1.4
7           3.4            1.5
8           2.9            1.4
9           3.1            1.5

In [33]:
df.isnull().any()

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [34]:
df.isnull().sum(axis = 1)

0      0
1      0
2      0
3      0
4      0
      ..
145    0
146    0
147    0
148    0
149    0
Length: 150, dtype: int64

In [35]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [36]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [37]:
df.SepalLengthCm.isnull().sum()

np.int64(0)

In [38]:
df['PetalLengthCm']= df['PetalLengthCm'].astype("int")

In [54]:
df['SepalLengthCm'] = df['SepalWidthCm'].astype("int")

In [53]:
x = df[['Id']].values.astype(float)

In [39]:
#to normalize data by tranforming them into specific fixed range(0 to 1)

from sklearn import preprocessing
x = df[['SepalLengthCm']].values.astype(float)
min_max_scaler = preprocessing.MinMaxScaler() 
x_scaled = min_max_scaler.fit_transform(x)
df_normalized = pd.DataFrame(x_scaled) 
df_normalized

            0
0    0.222222
1    0.166667
2    0.111111
3    0.083333
4    0.194444
..        ...
145  0.666667
146  0.555556
147  0.611111
148  0.527778
149  0.444444

[150 rows x 1 columns]

In [40]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [41]:
label_encoder = preprocessing.LabelEncoder()

In [42]:
df['Species']= label_encoder.fit_transform(df['Species'])

In [43]:
df['Species'].unique()

array([0, 1, 2])

In [44]:
features_df=df.drop(columns=['Species'])

In [55]:
#OneHotEncoder Creates new binary columns for each unique category

from sklearn.preprocessing import OneHotEncoder
enc = preprocessing.OneHotEncoder()

In [46]:
enc = preprocessing.OneHotEncoder() 
enc_df=pd.DataFrame(enc.fit_transform(df[['Species']]))
df_encode = features_df.join(enc_df)
df_encode

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,0
0,1,5.1,3.5,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
1,2,4.9,3.0,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
2,3,4.7,3.2,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
3,4,4.6,3.1,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
4,5,5.0,3.6,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
...,...,...,...,...,...,...
145,146,6.7,3.0,5,2.3,<Compressed Sparse Row sparse matrix of dtype ...
146,147,6.3,2.5,5,1.9,<Compressed Sparse Row sparse matrix of dtype ...
147,148,6.5,3.0,5,2.0,<Compressed Sparse Row sparse matrix of dtype ...
148,149,6.2,3.4,5,2.3,<Compressed Sparse Row sparse matrix of dtype ...
149,150,5.9,3.0,5,1.8,<Compressed Sparse Row sparse matrix of dtype ...

In [47]:
df_encode.rename(columns = {0:'Iris-Setosa', 
1:'Iris-Versicolor',2:'Iris-virginica'}, inplace = True)

In [48]:
df_encode

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Iris-Setosa
0,1,5.1,3.5,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
1,2,4.9,3.0,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
2,3,4.7,3.2,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
3,4,4.6,3.1,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
4,5,5.0,3.6,1,0.2,<Compressed Sparse Row sparse matrix of dtype ...
...,...,...,...,...,...,...
145,146,6.7,3.0,5,2.3,<Compressed Sparse Row sparse matrix of dtype ...
146,147,6.3,2.5,5,1.9,<Compressed Sparse Row sparse matrix of dtype ...
147,148,6.5,3.0,5,2.0,<Compressed Sparse Row sparse matrix of dtype ...
148,149,6.2,3.4,5,2.3,<Compressed Sparse Row sparse matrix of dtype ...
149,150,5.9,3.0,5,1.8,<Compressed Sparse Row sparse matrix of dtype ...

In [49]:
one_hot_df = pd.get_dummies(df, prefix="Species", 
columns=['Species'], drop_first=False)

In [50]:
one_hot_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_0,Species_1,Species_2
0,1,5.1,3.5,1,0.2,True,False,False
1,2,4.9,3.0,1,0.2,True,False,False
2,3,4.7,3.2,1,0.2,True,False,False
3,4,4.6,3.1,1,0.2,True,False,False
4,5,5.0,3.6,1,0.2,True,False,False
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5,2.3,False,False,True
146,147,6.3,2.5,5,1.9,False,False,True
147,148,6.5,3.0,5,2.0,False,False,True
148,149,6.2,3.4,5,2.3,False,False,True
149,150,5.9,3.0,5,1.8,False,False,True